driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-5.10
  - name: centos-6.5
  - name: fedora-19
  - name: fedora-20
  - name: freebsd-10.1

suites:
  - name: default
    run_list:
      - recipe[php::default]
